/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Doctor A. (https://sketchfab.com/doctorA)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tarisland-dragon-high-poly-ecf63885166c40e2bbbcdf11cd14e65f
Title: Tarisland - Dragon (High Poly)
*/

import React, { useRef,} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useTexture } from '@react-three/drei'
export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="M_B_44_Qishilong_skin_SkeletonFBX" rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M_B_44_Qishilong_skin" rotation={[-Math.PI / 2, 0, 0]} />
                  Hello-aman
                  <skinnedMesh  name="Object_7" geometry={nodes.Object_7.geometry} material={materials.MI_M_B_44_Qishilong_body02_Inst} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh  name="Object_8" geometry={nodes.Object_8.geometry} material={materials.MI_M_B_44_Qishilong_body02_2_Inst} skeleton={nodes.Object_8.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
